config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  resources :imports

  resources :clients

  resources :offers

  resources :sales

  resources :products

  get 'new/retail/sale' => 'sales#new_retail_sale'
  get 'new/whole/sale' => 'sales#new_whole_sale'
  get 'finish/sale/:id' => 'sales#end_sale'
  get 'trust/client/:id' => 'clients#trust'
  get 'untrust/client/:id' => 'clients#untrust'
  get '/finish/import/:id' => 'imports#end_import'

  post '/retail/sale' => 'sales#retail_sale'
  post '/whole/sale' => 'sales#whole_sale'

  root 'views#home'

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :import
  belongs_to :product
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new
    @delivery.product_id = params[:product_id]
    @delivery.import_id = params[:import_id]
    @delivery.amount = params[:amount]
    @delivery.price = params[:price]

    # product = Product.find(params[:product_id])
    # current_amount = product.amount
    # product.update(amount: (current_amount+params[:amount]))

    @delivery.save

    redirect_to :back
    # @delivery = Delivery.new(delivery_params)
    #
    # respond_to do |format|
    #   if @delivery.save
    #     format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
    #     format.json { render :show, status: :created, location: @delivery }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @delivery.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:import_id, :product_id, :price, :amount)
    end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_for(@delivery) do |f| %>
  <% if @delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
      <% @delivery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :import_id %><br>
    <%= f.text_field :import_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing delivery</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery %> |
<%= link_to 'Back', deliveries_path %>

app/views/deliveries/index.html.erb
<h1>Listing deliveries</h1>

<table>
  <thead>
    <tr>
      <th>Import</th>
      <th>Product</th>
      <th>Price</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.import %></td>
        <td><%= delivery.product %></td>
        <td><%= delivery.price %></td>
        <td><%= delivery.amount %></td>
        <td><%= link_to 'Show', delivery %></td>
        <td><%= link_to 'Edit', edit_delivery_path(delivery) %></td>
        <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery', new_delivery_path %>

app/views/deliveries/new.html.erb
<h1>New delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', deliveries_path %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Import:</strong>
  <%= @delivery.import %>
</p>

<p>
  <strong>Product:</strong>
  <%= @delivery.product %>
</p>

<p>
  <strong>Price:</strong>
  <%= @delivery.price %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @delivery.amount %>
</p>

<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
<%= link_to 'Back', deliveries_path %>