config/routes.rb
Rails.application.routes.draw do
  resources :deliveries

  resources :imports

  resources :clients

  resources :offers

  resources :sales

  resources :products

  get 'new/retail/sale' => 'sales#new_retail_sale'
  get 'new/whole/sale' => 'sales#new_whole_sale'
  get 'finish/sale/:id' => 'sales#end_sale'
  get 'trust/client/:id' => 'clients#trust'
  get 'untrust/client/:id' => 'clients#untrust'
  get '/finish/import/:id' => 'imports#end_import'

  post '/retail/sale' => 'sales#retail_sale'
  post '/whole/sale' => 'sales#whole_sale'

  root 'views#home'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new
    @offer.product_id = params[:product_id]
    @offer.sale_id = params[:sale_id]
    # @offer.amount =
    if params[:amount].to_i > Product.find(params[:product_id]).amount
      redirect_to @offer.sale, notice: 'There is insufficient inventory of ' + @offer.product.name + ' to complete that offer.'
    else
      @offer.amount = params[:amount]
      # product = Product.find(params[:product_id])
      # current_amount = product.amount
      # product.update(amount: (current_amount+params[:amount]))

      if params[:sale_type] == 'retail'
        @offer.price = Product.find(params[:product_id]).retail_price
      else
        @offer.price = Product.find(params[:product_id]).whole_sale_price
      end
      @offer.save

      redirect_to :back
    end


    # respond_to do |format|
    #   if @offer.save
    #     format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
    #     format.json { render :show, status: :created, location: @offer }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @offer.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      # params.require(:offer).permit(:product_id, :sale_id, :amount, :sale_type)
      params.permit(:product_id, :sale_id, :amount, :sale_type)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.text_field :sale_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Sale</th>
      <th>Price</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.product %></td>
        <td><%= offer.sale %></td>
        <td><%= offer.price %></td>
        <td><%= offer.amount %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @offer.product %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @offer.sale %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @offer.amount %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>